export const masterAddress = "server.tournamentassistant.net";
export const masterPort = "8676";
export const masterApiPort = "8678";
export const version = "1.2.4";
export const versionCode = 1240;

export type Permission =
  | "tournament:view_tournament_in_list"
  | "tournament:join"
  | "tournament:settings:add_authorized_users"
  | "tournament:settings:update_authorized_user_roles"
  | "tournament:settings:remove_authorized_users"
  | "tournament:settings:get_authorized_users"
  | "tournament:settings:get_discord_info"
  | "tournament:qualifier:get_qualifier_scores"
  | "tournament:qualifier:submit_qualifier_scores"
  | "tournament:qualifier:see_hidden_qualifier_scores"
  | "tournament:qualifier:get_remaining_attempts"
  | "tournament:qualifier:refund_attempts"
  | "tournament:player:return_to_menu"
  | "tournament:player:play_song"
  | "tournament:player:play_with_stream_sync"
  | "tournament:player:modify_gameplay"
  | "tournament:player:load_song"
  | "tournament:match:create_match"
  | "tournament:match:add_user_to_match"
  | "tournament:match:remove_user_from_match"
  | "tournament:match:set_match_leader"
  | "tournament:match:set_match_map"
  | "tournament:match:delete_match"
  | "tournament:qualifier:create"
  | "tournament:qualifier:set_name"
  | "tournament:qualifier:set_image"
  | "tournament:qualifier:set_info_channel"
  | "tournament:qualifier:set_flags"
  | "tournament:qualifier:set_leaderboard_sort"
  | "tournament:qualifier:add_maps"
  | "tournament:qualifier:update_map"
  | "tournament:qualifier:remove_map"
  | "tournament:qualifier:delete"
  | "tournament:settings:set_name"
  | "tournament:settings:set_image"
  | "tournament:settings:set_enable_teams"
  | "tournament:settings:set_enable_pools"
  | "tournament:settings:set_show_tournament_button"
  | "tournament:settings:set_show_qualifier_button"
  | "tournament:settings:set_allow_unauthorized_view"
  | "tournament:settings:set_score_update_frequency"
  | "tournament:settings:set_banned_mods"
  | "tournament:settings:add_team"
  | "tournament:settings:set_team_name"
  | "tournament:settings:set_team_image"
  | "tournament:settings:remove_team"
  | "tournament:settings:add_pool"
  | "tournament:settings:set_pool_name"
  | "tournament:settings:set_pool_image"
  | "tournament:settings:add_pool_maps"
  | "tournament:settings:update_pool_maps"
  | "tournament:settings:remove_pool_maps"
  | "tournament:settings:remove_pools"
  | "tournament:settings:add_role"
  | "tournament:settings:set_role_name"
  | "tournament:settings:set_role_permissions"
  | "tournament:settings:remove_role"
  | "tournament:settings:delete";
